// projects

export const START_PROJECTS_METADATA_LOAD	= "START_PROJECTS_METADATA_LOAD"
export const PROJECTS_METADATA_LOAD_SUCCESS = "PROJECTS_METADATA_LOAD_SUCCESS"
export const PROJECTS_METADATA_LOAD_ERROR 	= "PROJECTS_METADATA_LOAD_ERROR"

export const START_PROJECT_CREATION			= "START_PROJECT_CREATION"
export const PROJECT_CREATION_SUCCESS		= "PROJECT_CREATION_SUCCESS"
export const PROJECT_CREATION_ERROR			= "PROJECT_CREATION_ERROR"

export const START_PROJECT_DELETE			= "START_PROJECT_DELETE"
export const PROJECT_DELETE_SUCCESS			= "PROJECT_DELETE_SUCCESS"
export const PROJECT_DELETE_ERROR			= "PROJECT_DELETE_ERROR"

export const RUN_PROJECT_EDITOR 			= "RUN_PROJECT_EDITOR"

// editor

// ui
export const GO_TO_PAGE						= "GO_TO_PAGE"
export const SET_SELECTED_LAYERS			= "SET_SELECTED_LAYERS"
export const UPDATE_MOTION_CAPTURE_DATA		= "UPDATE_MOTION_CAPTURE_DATA"
export const UPDATE_BUBBLE_VARIABLES		= "UPDATE_BUBBLE_VARIABLES"

// project
export const START_PROJECT_LOAD				= "START_PROJECT_LOAD"
export const PROJECT_LOAD_SUCCESS			= "PROJECT_LOAD_SUCCESS"
export const PROJECT_LOAD_ERROR				= "PROJECT_LOAD_ERROR"
export const ADD_PAGE						= "ADD_PAGE"
export const DELETE_PAGE					= "DELETE_PAGE"
export const REORDER_PAGES					= "REORDER_PAGES"
export const START_LAYER_ADD				= "START_LAYER_ADD"
export const LAYER_ADD_SUCCESS				= "LAYER_ADD_SUCCESS"
export const LAYER_ADD_ERROR				= "LAYER_ADD_ERROR"
export const DELETE_LAYER					= "DELETE_LAYER"
export const SET_LAYER_ORDER				= "SET_LAYER_ORDER"
export const UPDATE_LAYER_VARIABLES			= "UPDATE_LAYER_VARIABLES"
export const ADD_BALLOON					= "ADD_BALLOON"
export const UPDATE_BALLOON_DATA_VARIABLES	= "UPDATE_BALLOON_DATA_VARIABLES"

// (shared)

export const EXIT_PROJECT					= "EXIT_PROJECT"